### ISSUE TITLE
Map geojsons failing to load over HTTPS

### ISSUE THREAD

**Issue by bplmp** [596acres/livinglots-nyc#1]
When I load Living Lots over HTTPS (which I believe is default) the geojsons are failing to load because they're requested over HTTP. This causes the main map to not display any points. Loading the page over HTTP works fine.

![chrome console errors](https://cloud.githubusercontent.com/assets/11858154/21993636/03a0524c-dc03-11e6-86f1-755778c7b2cc.png)

**Comment by ebrelsford** [comment]
This is fixed @bplmp, thanks again for the reminder!

**Comment by bplmp** [comment]
yay, thanks! Working perfectly here :star:
